[serialize-to-javascript-impl]
spec = "serialize-to-javascript-impl.spec"
build_script = ""
build_method = "mock"
owner = "your koji username"
git_repo = "https://github.com/ultramarine-linux/serialize-to-javascript-impl"
