[rust-serialize-to-javascript-impl]
spec = "serialize-to-javascript-impl.spec"
build_script = ""
build_method = "mock"
owner = "cappy"
git_repo = "https://github.com/ultramarine-linux/pkg-rust-serialize-to-javascript-impl"
